###
POST http://localhost:5000/api/adminregister
Content-Type: application/json

{
  "name": "jothinathan",
  "email": "jothinathannagarajan@gmail.com",
  "password": "123"
  
}

###
POST http://localhost:5000/api/hodregister
Content-Type: application/json

{
  "name": "Dr.Punar",
  "email": "punar.it@department.com",
  "password": "9876",
  "department": "IT"
}

