### Admin Login to get token
POST http://localhost:5000/api/admin/adminlogin
Content-Type: application/json

{
  "email": "jothinathannagarjan@gmail.com@gmail.com",
  "password": "1234"
}

### heads insert
POST http://localhost:5000/api/admin-head/headinsert
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvdGhpbmF0aGFubmFnYXJqYW5AZ21haWwuY29tQGdtYWlsLmNvbSIsImlkIjoiNjdmNTJiMTRhYmVkMWE5YjMxMWE4YzU0IiwiaWF0IjoxNzQ0MTIwNzM1LCJleHAiOjE3NDQxMjQzMzV9.swXmw_sbdH5GcRNU401z9foBZheLalEuyMkcD30FspQ


{
  "id": "22it033",
  "name": "jothinathan",
  "email": "jothinathan@gmail.com",
  "password": "123",
  "designation" : "join secretary"
}

###get all heads
GET http://localhost:5000/api/admin-head/getallheads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvdGhpbmF0aGFubmFnYXJqYW5AZ21haWwuY29tQGdtYWlsLmNvbSIsImlkIjoiNjdmNTJiMTRhYmVkMWE5YjMxMWE4YzU0IiwiaWF0IjoxNzQ0MTIwNjYwLCJleHAiOjE3NDQxMjQyNjB9.TIR4HtqV8zD6sHP1YtBcZ2ODyWM5joiKDBbK_oM4vmU


####remove head by id
DELETE http://localhost:5000/api/admin-head/deleteheadbyid/22it020
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvdGhpbmF0aGFubmFnYXJqYW5AZ21haWwuY29tQGdtYWlsLmNvbSIsImlkIjoiNjdmNTJiMTRhYmVkMWE5YjMxMWE4YzU0IiwiaWF0IjoxNzQ0MTIwNjYwLCJleHAiOjE3NDQxMjQyNjB9.TIR4HtqV8zD6sHP1YtBcZ2ODyWM5joiKDBbK_oM4vmU


{
  "id": "22it020"
}


