### Admin Login to get token
POST http://localhost:5000/api/admin/adminlogin
Content-Type: application/json

{
  "email": "ruby@gmail.com",
  "password": "0103"
}

### Insert Class Advisor
POST http://localhost:5000/api/ca/insert
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1YnlAZ21haWwuY29tIiwiaWQiOiI2N2YzZmNhYWNjNGJhY2QxOGU3YjVlY2EiLCJpYXQiOjE3NDQxMjUyMzIsImV4cCI6MTc0NDEyNTgzMn0.rytJk_GKsJ-P8wkq6jqETw4cQstmiP_BC29006hv8qU

{
  "name": "Romika T",
  "department": "IT",
  "section": "B",
  "email": "romika@gmail.com",
  "password":"1234"
}

### Delete Class Advisor
DELETE http://localhost:5000/api/ca/delete/romika@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1YnlAZ21haWwuY29tIiwiaWQiOiI2N2YzZmNhYWNjNGJhY2QxOGU3YjVlY2EiLCJpYXQiOjE3NDQxMjUyMzIsImV4cCI6MTc0NDEyNTgzMn0.rytJk_GKsJ-P8wkq6jqETw4cQstmiP_BC29006hv8qU


### View Class Advisors
GET http://localhost:5000/api/ca/viewCas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1YnlAZ21haWwuY29tIiwiaWQiOiI2N2YzZmNhYWNjNGJhY2QxOGU3YjVlY2EiLCJpYXQiOjE3NDQxMjUyMzIsImV4cCI6MTc0NDEyNTgzMn0.rytJk_GKsJ-P8wkq6jqETw4cQstmiP_BC29006hv8qU
