### Admin Login
POST http://localhost:5000/api/admin/adminlogin
Content-Type: application/json

{
  "email": "ruby@gmail.com",
  "password": "0103"
  
}


### Admin Login to get token
POST http://localhost:5000/api/ca/calogin
Content-Type: application/json

{
  "email": "preethi@gmail.com",
  "password": "2515"
}

### Insert Class Advisor
POST http://localhost:5000/api/ca/insert
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbmpheUBnbWFpbC5jb20iLCJpZCI6IjY3ZjU0OGJlMWY0NTY3Zjc0MWVmYTkxMCIsImlhdCI6MTc0NDIwNjM4MSwiZXhwIjoxNzQ0MjA2OTgxfQ.hNcxaPJzhyNdgpa9wU80z98aMgfOow_T09arl2SpDQk

{
  "name": "Karthika S S",
  "department": "IT",
  "section": "A",
  "email": "karthika@gmail.com",
  "password":"1234"
}

### Delete Class Advisor
DELETE http://localhost:5000/api/ca/delete/romika@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1YnlAZ21haWwuY29tIiwiaWQiOiI2N2YzZmNhYWNjNGJhY2QxOGU3YjVlY2EiLCJpYXQiOjE3NDQxMjUyMzIsImV4cCI6MTc0NDEyNTgzMn0.rytJk_GKsJ-P8wkq6jqETw4cQstmiP_BC29006hv8qU


### View Class Advisors
GET http://localhost:5000/api/ca/viewCas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbmpheUBnbWFpbC5jb20iLCJpZCI6IjY3ZjU0OGJlMWY0NTY3Zjc0MWVmYTkxMCIsImlhdCI6MTc0NDIwNjM4MSwiZXhwIjoxNzQ0MjA2OTgxfQ.hNcxaPJzhyNdgpa9wU80z98aMgfOow_T09arl2SpDQk

###Filter by Departments
GET http://localhost:5000/api/ca/filterByDepartment/CY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZWV0aGlAZ21haWwuY29tIiwiaWQiOiI2N2Y2N2JhNzQxZTczYWMwOTM3NDUwYTUiLCJpYXQiOjE3NDQyMDg4NTQsImV4cCI6MTc0NDIwOTQ1NH0.fF9lNn-aVt0HOuRFAJuM1KAVx8YJ7y8lP2r4hGTeKzY