### Admin Register
POST http://localhost:5000/api/admin/adminregister
Content-Type: application/json

{
  "name": "jothinathan",
  "email": "jothinathannagarjan@gmail.com@gmail.com",
  "password": "1234"
  
}

### Admin Login
POST http://localhost:5000/api/admin/adminlogin
Content-Type: application/json

{
  "email": "ruby@gmail.com",
  "password": "0103"
  
}